Enforce ```python

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -12,6 +12,18 @@ jobs:
       - uses: actions/checkout@v4
       - run: shellcheck --color=always --shell=bash --exclude=SC2086,SC2059,SC2046,SC2235,SC2002,SC2206,SC2068,SC2207,SC2013 *.sh activate
 
+  # For consistency, Jou code in markdown files should use ```python, not ```python3
+  python-in-markdown:
+    timeout-minutes: 1
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - run: |
+          if git grep '```python3' || git grep '```py$' || git grep '```py3$'; then
+            echo 'Error: Jou code in markdown files must be marked with ```python'
+            exit 1
+          fi
+
   editorconfig-checker:
     timeout-minutes: 1
     runs-on: ubuntu-latest
